main/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    UserSignUpView,
    SignUpDoneView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='main/account_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main:index'), name='logout'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('signup/done/<int:pk>', SignUpDoneView.as_view(), name='signup_done'),
]

main/roles/zakupschik/urls.py
from django.urls import path, re_path
import main.roles.zakupschik.views as views

urlpatterns = [
    path('', views.ZakupschikMainView.as_view(), name='zakupschik'),
    path('locations/', views.ZakupschikLocationsView.as_view(), name='zakupschik_locations'),
    re_path(r'^locations/places/(?P<place>[/\-\w]+)/$', views.ZakupschikOrderItemsByPlaceView.as_view(), name='zakupschik_order_details_by_place'),
    re_path(r'locations/(?P<location>[/\w]+)/(?P<floor>[/\w]+)/(?P<line>[/\w]+)/$', views.ZakupschikPlacesView.as_view(), name='zakupschik_places'),
    re_path(r'locations/(?P<location>[/\w]+)/(?P<floor>[/\w]+)/$', views.ZakupschikLocationsLinesView.as_view(), name='zakupschik_locations_lines'),
    re_path(r'locations/(?P<location>[/\w]+)/$', views.ZakupschikLocationsFloorsView.as_view(), name='zakupschik_locations_floors'),
    path('products_to_deliver/', views.ZakupschikUsersWithProductsToDeliverView.as_view(), name='zakupschik_products_ready_to_delivery'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as main_views
from .roles import urls as roles_urls
from .accounts import urls as accounts_urls
from rest_framework.routers import DefaultRouter

app_name = 'main'

router = DefaultRouter()
router.register('users', main_views.UsersResourceView)
router.register('orders', main_views.OrdersResourceView)
router.register('providers', main_views.ProvidersResourceView)

urlpatterns = [
    path('', main_views.IndexView.as_view(), name='index'),
    path('roles/', include(roles_urls)),
    path('accounts/', include(accounts_urls)),
    path('providers/', main_views.ProvidersListView.as_view(), name='providers'),
    path('users/', main_views.UsersListView.as_view(), name='users'),
    path('users/<int:pk>/', main_views.UserDetailsView.as_view(), name='user_details'),
    path('users/<int:pk>/delete', main_views.DeleteUserView.as_view(), name='delete_user'),
    path('products/', main_views.ProductsListView.as_view(), name='products'),
    path('products/<int:pk>/add_to_order/', main_views.ProductsAddToOrderView.as_view(), name='details'),
    path('products/<int:pk>/add_to_order/<int:order_pk>', main_views.ProductsAddToOrderView.as_view(), name='details'),
    path('products/new_joint_product/', main_views.NewJointProductView.as_view(), name='new_joint_product'),
    path('products/<int:pk>', main_views.UpdateProductView.as_view(), name='update_product'),
    path('products/<int:pk>/delete/', main_views.DeleteProductView.as_view(), name='delete_product'),
    path('buyouts/', main_views.BuyoutsListView.as_view(), name='buyouts'),
    path('help/', main_views.HelpView.as_view(), name='help'),
    path('news/', main_views.NewsView.as_view(), name='news'),
    path('edit_news/', main_views.EditNewsView.as_view(), name='edit_news'),

    # Order related
    path('new_order/', main_views.NewOrderView.as_view(), name='new_order'),
    path('orders/', main_views.OrdersListView.as_view(), name='orders'),
    path('orders/<int:pk>/', main_views.OrderDetailsView.as_view(), name='order_details'),
    path('orders/<int:pk>/delete/', main_views.DeleteOrderView.as_view(), name='delete_order'),
    path('orders/<int:pk>/pay_done/', main_views.OrderPayingView.as_view(), name='order_paying'),
    path('orders/<int:pk>/paying/', main_views.JointReceiptForOrderView.as_view(), name='receipt_for_order'),
    path('orders/<int:pk>/new_item/', main_views.NewOrderItemView.as_view(), name='new_order_item'),
    path('orders/<int:pk>/new_joint_item/', main_views.NewJointOrderItemView.as_view(), name='new_joint_order_item'),
    path('orders/<int:pk>/delete/', main_views.DeleteOrderView.as_view(), name='delete_order'),
    path('orders/<int:pk>/joint_item_to_product/<int:product_pk>', main_views.NewJointOrderItemView.as_view(),
         name='joint_item_to_product'),
    path('orders/joint_item_to_product/<int:product_pk>', main_views.NewJointOrderItemView.as_view(),
         name='joint_item_to_product_new_order'),
    path('orders/product_to_order/<int:product_id>', main_views.OrdersListView.as_view(), name='product_to_orders'),

    path('order_item/<int:pk>', main_views.OrderItemView.as_view(), name='order_item_details'),
    path('order_item/<int:pk>/new_replacement/', main_views.ReplacementOrderItemView.as_view(),
         name='replacement_order_item'),
    path('order_item/<int:pk>/delete/', main_views.DeleteOrderItemView.as_view(), name='delete_order_item'),

    # Catalog items
    path('catalog/', main_views.CatalogOrderItems.as_view(), name='catalog'),
    path('catalog/<int:pk>/', main_views.CatalogOrderItems.as_view(), name='catalog'),

    path('settings/', main_views.SettingsView.as_view(), name='settings'),

    # Django REST framework related
    path('api/', include(router.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_posrednik/urls.py
from django.contrib import admin
from django.urls import path, include

# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            Test Shop Title
        {% endblock %}
    </title>
    <!-- Bootstrap CSS -->
    {#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Main styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- PhotoSwipe CSS -->
    <link rel="stylesheet" href="{% static 'PhotoSwipe/photoswipe.css' %}">
    <link rel="stylesheet" href="{%  static 'PhotoSwipe/default-skin/default-skin.css' %}">
    <!-- Bootstrap CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/4.0.9/jquery.inputmask.bundle.min.js"></script>#}
    <script src="{% static '/js/jquery.inputmask.bundle.min.js' %}"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light mt-2 bg-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">{{ shop_title }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbars">
        <ul class="navbar-nav">
            {% if user_is_authenticated %}
                <li class="nav-item">
                    <div class="d-flex mr-auto col-sm-auto">
                        <a class="nav-link disabled text-dark" aria-disabled="true">Привет, </a>
                        <a class="nav-link text-primary" href="{% url 'main:user_details' pk=user_pk %}">{{ user_first_name }}</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled text-dark" tabindex="-1" aria-disabled="true">Баланс: {{ user_balance }}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Личный кабинет</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if user_role == roles.ADMINISTRATOR %}
                            <a class="dropdown-item" href="{% url 'main:orders' %}">Заказы</a>
                            <a class="dropdown-item" href="{% url 'main:zakupschik_locations' %}">Заказы на выкуп</a>
                            <a class="dropdown-item" href="{% url 'main:products' %}">Выкупы</a>
                            <a class="dropdown-item" href="{% url 'main:users' %}">Пользователи</a>
                            <a class="dropdown-item" href="{% url 'main:providers' %}">Поставщики</a>
                            <a class="dropdown-item" href="{% url 'main:edit_news' %}">Раздел новостей</a>
                            <a class="dropdown-item" href="{% url 'main:settings' %}">Настройки сайта</a>
                            <a class="dropdown-item" href="{% url 'main:user_details' pk=user_pk %}">Настройки
                                профиля</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        {% elif user_role == roles.ZAKUPSCHIK %}
                            <a class="dropdown-item" href="{% url 'main:zakupschik_locations' %}">Заказы на
                                выкуп</a>
                            <a class="dropdown-item" href="{% url 'main:zakupschik_products_ready_to_delivery' %}">Выдача
                                товаров</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        {% else %} {# 'ZAKAZSCHIK' #}
                            <a class="dropdown-item" href="{% url 'main:new_order' %}">Новый заказ</a>
                            <a class="dropdown-item" href="{% url 'main:orders' %}">Мои заказы</a>
                            <a class="dropdown-item" href="{% url 'main:catalog' %}">Выкупы</a>
                            <a class="dropdown-item" href="{% url 'main:user_details' pk=user_pk %}">Настройки</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        {% endif %}
                    </div>
                </li>
            {% else %}
                    <div class="btn-group my-2">
                        <a class="btn btn-sm btn-outline-secondary " href="{% url 'main:signup' %}">Регистрация</a>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'main:login' %}">Войти</a>
                    </div>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

{% block content %}
    No content
{% endblock %}
<footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</footer>
</body>
</html>