main/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    UserSignUpView,
    SignUpDoneView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='main/account_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main:index'), name='logout'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('signup/done/<int:pk>', SignUpDoneView.as_view(), name='signup_done'),
]

main/roles/urls.py
from django.urls import path, include
from .zakazschik import urls as zakazschik_urls
from .zakupschik import urls as zakupschik_urls
from .administrator import urls as administrator_urls


urlpatterns = [
    path('zakazschik/', include(zakazschik_urls)),
    path('zakupschik/', include(zakupschik_urls)),
    path('administrator/', include(administrator_urls)),
]

main/roles/zakupschik/urls.py
from django.urls import path, re_path
import main.roles.zakupschik.views as views

urlpatterns = [
    path('', views.ZakupschikMainView.as_view(), name='zakupschik'),
    path('locations/', views.ZakupschikLocationsView.as_view(), name='zakupschik_locations'),
    re_path(r'^locations/places/(?P<place>[/\-\w]+)/$', views.ZakupschikOrderItemsByPlaceView.as_view(), name='zakupschik_order_details_by_place'),
    re_path(r'locations/(?P<location>[/\w]+)/(?P<floor>[/\w]+)/(?P<line>[/\w]+)/$', views.ZakupschikPlacesView.as_view(), name='zakupschik_places'),
    re_path(r'locations/(?P<location>[/\w]+)/(?P<floor>[/\w]+)/$', views.ZakupschikLocationsLinesView.as_view(), name='zakupschik_locations_lines'),
    re_path(r'locations/(?P<location>[/\w]+)/$', views.ZakupschikLocationsFloorsView.as_view(), name='zakupschik_locations_floors'),
    path('products_to_deliver/', views.ZakupschikUsersWithProductsToDeliverView.as_view(), name='zakupschik_products_ready_to_delivery'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as main_views
from .roles import urls as roles_urls
from .accounts import urls as accounts_urls
from rest_framework.routers import DefaultRouter

app_name = 'main'

router = DefaultRouter()
router.register('users', main_views.UsersResourceView)
router.register('orders', main_views.OrdersResourceView)
router.register('providers', main_views.ProvidersResourceView)

urlpatterns = [
    path('', main_views.IndexView.as_view(), name='index'),
    path('roles/', include(roles_urls)),
    path('accounts/', include(accounts_urls)),
    path('providers/', main_views.ProvidersListView.as_view(), name='providers'),
    path('users/', main_views.UsersListView.as_view(), name='users'),
    path('users/<int:pk>/', main_views.UserDetailsView.as_view(), name='user_details'),
    path('users/<int:pk>/delete', main_views.DeleteUserView.as_view(), name='delete_user'),
    path('products/', main_views.ProductsListView.as_view(), name='products'),
    path('products/<int:pk>/add_to_order/', main_views.ProductsAddToOrderView.as_view(), name='details'),
    path('products/<int:pk>/add_to_order/<int:order_pk>', main_views.ProductsAddToOrderView.as_view(), name='details'),
    path('products/new_joint_product/', main_views.NewJointProductView.as_view(), name='new_joint_product'),
    path('products/<int:pk>', main_views.UpdateProductView.as_view(), name='update_product'),
    path('products/<int:pk>/delete/', main_views.DeleteProductView.as_view(), name='delete_product'),
    path('buyouts/', main_views.BuyoutsListView.as_view(), name='buyouts'),
    path('help/', main_views.HelpView.as_view(), name='help'),
    path('news/', main_views.NewsView.as_view(), name='news'),
    path('edit_news/', main_views.EditNewsView.as_view(), name='edit_news'),

    # Order related
    path('new_order/', main_views.NewOrderView.as_view(), name='new_order'),
    path('orders/', main_views.OrdersListView.as_view(), name='orders'),
    path('orders/<int:pk>/', main_views.OrderDetailsView.as_view(), name='order_details'),
    path('orders/<int:pk>/delete/', main_views.DeleteOrderView.as_view(), name='delete_order'),
    path('orders/<int:pk>/pay_done/', main_views.OrderPayingView.as_view(), name='order_paying'),
    path('orders/<int:pk>/paying/', main_views.JointReceiptForOrderView.as_view(), name='receipt_for_order'),
    path('orders/<int:pk>/new_item/', main_views.NewOrderItemView.as_view(), name='new_order_item'),
    path('orders/<int:pk>/new_joint_item/', main_views.NewJointOrderItemView.as_view(), name='new_joint_order_item'),
    path('orders/<int:pk>/delete/', main_views.DeleteOrderView.as_view(), name='delete_order'),
    path('orders/<int:pk>/joint_item_to_product/<int:product_pk>', main_views.NewJointOrderItemView.as_view(),
         name='joint_item_to_product'),
    path('orders/joint_item_to_product/<int:product_pk>', main_views.NewJointOrderItemView.as_view(),
         name='joint_item_to_product_new_order'),
    path('orders/product_to_order/<int:product_id>', main_views.OrdersListView.as_view(), name='product_to_orders'),

    path('order_item/<int:pk>', main_views.OrderItemView.as_view(), name='order_item_details'),
    path('order_item/<int:pk>/new_replacement/', main_views.ReplacementOrderItemView.as_view(),
         name='replacement_order_item'),
    path('order_item/<int:pk>/delete/', main_views.DeleteOrderItemView.as_view(), name='delete_order_item'),

    # Catalog items
    path('catalog/', main_views.CatalogOrderItems.as_view(), name='catalog'),
    path('catalog/<int:pk>/', main_views.CatalogOrderItems.as_view(), name='catalog'),

    path('settings/', main_views.SettingsView.as_view(), name='settings'),

    # Django REST framework related
    path('api/', include(router.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_posrednik/urls.py
from django.contrib import admin
from django.urls import path, include

# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
import os.path
import shutil
from decimal import Decimal
from django.core.exceptions import ObjectDoesNotExist
from django.db import models, transaction
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.signals import pre_delete, post_delete
from django.conf import settings
from django.utils.translation import ugettext as _u
from main.core.models import ModelWithTimestamp, ModelWithUser
from main.core.constants import (
    OrderStatuses,
    Roles,
    OrderItemStatuses,
    OrderItemStates,
    ShoppingTypes,
    PurchaseAndDeliveryTypes,
    DeliveryTypes,
    DELIVERY_PRICES,
)
from main.core.utils import get_file_hash

MEDIA_PROD_IMAGE_DIR_PREFFIX = 'product_images'
MEDIA_ORDER_DIR_PREFFIX = 'order_'
MEDIA_SETTINGS_IMAGES_DIR_PREFFIX = 'settings_images'


# Create your models here.
class Provider(models.Model):
    name = models.CharField(max_length=256)
    vk_link = models.CharField(max_length=256)
    place = models.CharField(verbose_name='Место', max_length=150, default='')
    description = models.TextField(blank=True, default='')
    picture = models.CharField(max_length=256)
    product_type = models.CharField(max_length=256, blank=True, default='')


class UserBalance(ModelWithTimestamp):
    user = models.ForeignKey('User', on_delete=models.CASCADE, blank=True, null=True)
    delta = models.DecimalField(max_digits=10, decimal_places=2)


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_u('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_u('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_u('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

    def get_list(self, **kwargs):
        return self.filter(is_staff=False, is_superuser=False, **kwargs)


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    username = None
    email = models.EmailField('Email', unique=True)
    phone = models.CharField('Телефон', max_length=20)
    delivery_address = models.CharField('Адрес доставки', max_length=255)
    birth_date = models.DateField('Дата рождения', blank=True, null=True)
    role = models.PositiveSmallIntegerField('Роль', choices=tuple(Roles), default=Roles.UNREGISTERED)

    objects = CustomUserManager()

    class Meta:
        ordering = ('role',)

    def __str__(self):
        return self.email

    @property
    def role_to_string(self):
        return Roles[self.role]

    @property
    def balance(self):
        return sum(UserBalance.objects.filter(user=self).values_list('delta', flat=True))

    def update_balance_with_delta(self, new_delta):
        if new_delta:
            from main.emails import user_data_email
            UserBalance.objects.create(user=self, delta=new_delta)
            user_data_email(user=self,
                            subject='Баланс пользователя изменен',
                            extra_params={'balance_changed': True})


class OrderManager(models.Manager):

    def get_list(self, **kwargs):
        return self.filter(**kwargs).order_by('status')


class Order(ModelWithTimestamp, ModelWithUser):
    objects = OrderManager()

    status = models.PositiveSmallIntegerField(default=OrderStatuses.CREATED, choices=tuple(OrderStatuses))
    paid_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
    actual_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
    delivery = models.PositiveSmallIntegerField(default=DeliveryTypes.PICKUP, choices=tuple(DeliveryTypes))

    @property
    def price(self):
        order_items_qs = OrderItem.objects.get_used(order=self)
        extra_charge = SettingOptionHandler('extra_charge').value
        extra_delivery_price = dict(DELIVERY_PRICES)[self.delivery]
        return (
                       sum(oi.price * oi.quantity for oi in order_items_qs.filter(
                           delivery=PurchaseAndDeliveryTypes.PURCHASE_AND_DELIVERY
                       )) * (1 + extra_charge / 100) +
                       sum(oi.price * oi.quantity for oi in order_items_qs.filter(
                           delivery=PurchaseAndDeliveryTypes.DELIVERY_ONLY
                       )) * (extra_charge / 100)
               ) + extra_delivery_price

    @property
    def actual_price_diff(self):
        return self.actual_price - self.price

    @property
    def status_to_string(self):
        return OrderStatuses[self.status]

    @property
    def delivery_to_string(self):
        return DeliveryTypes[self.delivery]

    @property
    def delivery_address(self):
        if self.created_by:
            return self.created_by.delivery_address
        return ''

    @delivery_address.setter
    def delivery_address(self, value):
        if self.created_by:
            self.created_by.delivery_address = value
            self.created_by.save()

    @property
    def all_prices_updated(self):
        if self.orderitem_set.filter(product__price=0).count():
            return False
        return True

    @property
    def top_order_items(self):
        return self.orderitem_set.filter(parent__isnull=True)

    def _update_price_and_balance(self):
        # The actual price and user balance is updated only for orders in process
        # After it is finished it is frozen for future statistic for example
        price_delta = self.actual_price_diff
        if price_delta:
            if self.status in (OrderStatuses.PAYING_TO_BE_CONFIRMED,
                               OrderStatuses.PAID,
                               OrderStatuses.IN_PROGRESS):
                # Update user balance first
                user = self.created_by
                if user:
                    user.update_balance_with_delta(price_delta)
            self.actual_price = self.price
            return True
        return False

    def pay_order(self):
        self.status = OrderStatuses.PAYING_TO_BE_CONFIRMED
        user = self.created_by
        if user:
            with transaction.atomic():
                super().save()
                user.update_balance_with_delta(-self.actual_price)
            from main.emails import order_data_email
            order_data_email(order=self,
                             subject='Новый заказ №{}'.format(self.pk),
                             extra_params={'status_changed': True})

    @transaction.atomic
    def update_actual_price_with_user_balance(self):
        self.refresh_from_db()
        if self._update_price_and_balance():
            super().save(update_fields=['actual_price'],)

    @transaction.atomic
    def save(self, **kwargs):
        self._update_price_and_balance()
        super().save(**kwargs)


class OrderItemManager(models.Manager):

    def get_list(self, **kwargs):
        return self.filter(state__in=(OrderItemStates.ACTIVE, OrderItemStates.USED), **kwargs)

    def get_used(self, **kwargs):
        return self.filter(state=OrderItemStates.USED, **kwargs)


class OrderItem(ModelWithTimestamp, ModelWithUser):
    objects = OrderItemManager()

    product = models.ForeignKey('Product', verbose_name='Продукт', on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, verbose_name='Заказ', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)
    order_comment = models.TextField(verbose_name='Комментарий к заказу', max_length=255, blank=True, default='')
    customer_comment = models.TextField(verbose_name='Комментарий заказчика', max_length=255, blank=True, default='')
    status = models.PositiveSmallIntegerField(verbose_name='Статус',
                                              default=OrderItemStatuses.CREATED,
                                              choices=tuple(OrderItemStatuses))
    state = models.PositiveSmallIntegerField(verbose_name='Состояние',
                                             default=OrderItemStates.USED,
                                             choices=tuple(OrderItemStates))
    parent = models.OneToOneField('self', verbose_name='Заменяемый товар',
                                  on_delete=models.DO_NOTHING, null=True, blank=True, related_name='replacement')
    delivery = models.PositiveSmallIntegerField(verbose_name='Тип доставки',
                                                default=PurchaseAndDeliveryTypes.PURCHASE_AND_DELIVERY,
                                                choices=tuple(PurchaseAndDeliveryTypes))
    _price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    @property
    def status_to_string(self):
        return OrderItemStatuses[self.status]

    @property
    def delivery_to_string(self):
        return PurchaseAndDeliveryTypes[self.delivery]

    @property
    def place(self):
        return self.product.place if self.product else ''

    @property
    def name(self):
        return self.product.name if self.product else ''

    @property
    def price(self):

main/roles/administrator/views.py
from django.views.generic.base import TemplateView
from main.core.view_mixins import LoginRolesRequiredViewMixin, CommonContextViewMixin


class AdministratorMainView(LoginRolesRequiredViewMixin, CommonContextViewMixin, TemplateView):
    template_name = 'main/administrator.html'

main/roles/zakazschik/views.py
from django.views.generic.base import TemplateView
from main.core.view_mixins import LoginRolesRequiredViewMixin, CommonContextViewMixin
from main.core.constants import Roles


class ZakazschikMainView(LoginRolesRequiredViewMixin, CommonContextViewMixin, TemplateView):
    template_name = 'main/zakazschik.html'
    allowed_roles = (Roles.ZAKAZSCHIK,)

main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Магазин товаров{% endblock title %}


{% block content %}


    <div class="nav-scroller bg-white shadow-sm">
        <div class="container">
            <nav class="nav nav-underline d-flex justify-content-between">
              <a class="p-2 text-muted" href="{% url 'main:catalog' %}">Каталог товаров</a>
              <a class="p-2 text-muted" href="{% url 'main:news' %}">Новости</a>
              <a class="p-2 text-muted" data-toggle="modal" data-target="#ModalWork" href="#">Рабочие графики</a>
              <a class="p-2 text-muted" data-toggle="modal" data-target="#ModalContacts" href="#">Контакты</a>
              <a class="p-2 text-muted" data-toggle="modal" data-target="#ModalPartnership" href="#">Условия сотрудничества</a>
              <a class="p-2 text-muted" href="{% url 'main:providers' %}">Наши поставщики</a>
            </nav>
        </div>
      </div>

        {% include 'main/include/modal_window_template.html' with title="Рабочие графики" modal_lable="ModalWork" modal_body="<img class=\"d-block w-100\" src=\"https://sun9-54.userapi.com/c851236/v851236800/1c9ee8/eZePSOebxUs.jpg\">" %}

        {% include 'main/include/modal_window_template.html' with title="Контакты" modal_lable="ModalContacts" modal_body=contacts %}

        {% include 'main/include/modal_window_template.html' with title="Условия сотрудничества" modal_lable="ModalPartnership" modal_body="sadfgasf {{ announcement }} <p>" %}
    <div class="container">
        {# Announcement#}
         <div class="jumbotron jumbotron-fluid mt-3 p-md-3 text-secondary rounded bg-lg">
            <div class="col-md-6 px-0">
              <h1 class="display-5 font-italic">Обьявление</h1>
              <p class="lead my-3">{{ announcement }}</p>
              <p class="lead mb-0"><a href="#" class="text-secondary font-weight-bold">Подробее...</a></p>
            </div>
        </div>

        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://sun9-64.userapi.com/c850424/v850424659/1ea6af/2JrLzP4XSWI.jpg"
                alt="First slide">
            </div>
{#            <div class="carousel-item">#}
{#              <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(16).jpg"#}
{#                alt="Second slide">#}
{#            </div>#}
{#            <div class="carousel-item">#}
{#              <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(17).jpg"#}
{#                alt="Third slide">#}
{#            </div>#}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>

{% endblock content %}

main/templates/main/user_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Детальная информация{% endblock title %}

{% block content %}
    <h3 class="font-weight-normal text-center">
        Пользователь
    </h3>
    {% if messages %}
        {% for message in messages %}
            <div class="toast" data-delay="1500" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-body text-white bg-success">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <hr class="mb-4">
    <form class="form-signin my-3 p-3 bg-white rounded shadow-sm" name="setting" id="setting" action="" method="POST"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_username" class="col-5 col-form-label">Email пользователя</label>
            <div class="col-7">
                <input class="form-control" id="id_username" type="email" name="{{ form.email.name }}"
                       autofocus="" required="" value="{{ form.email.initial|default_if_none:'' }}"
                        {% if form.email.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.email.errors %}
                <div class="alert alert-danger">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label for="id_first_name" class="col-5 col-form-label">Имя</label>
            <div class="col-7">
                <input class="form-control" id="id_first_name" type="text" name="{{ form.first_name.name }}"
                       required="" value="{{ form.first_name.initial|default_if_none:'' }}"
                        {% if form.first_name.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.first_name.errors %}
                <div class="alert alert-danger">
                    {{ form.first_name.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label for="id_last_name" class="col-5 col-form-label">Фамилия</label>
            <div class="col-7">
                <input class="form-control" id="id_last_name" type="text" name="{{ form.last_name.name }}"
                       required="" value="{{ form.last_name.initial|default_if_none:'' }}"
                        {% if form.last_name.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.last_name.errors %}
                <div class="alert alert-danger">
                    {{ form.last_name.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label for="id_role" class="col-5 col-form-label">Роль</label>
            <div class="col-7">
                <select class="form-control" name="role" id="id_role"
                        {% if form.role.field.disabled %}
                        disabled=""
                        {% endif %}
                >
                    {% for role, role_str in roles_list %}
                        {% if role == object.role %}
                            <option value="{{ role }}" selected>{{ role_str }}</option>
                        {% else %}
                            <option value="{{ role }}">{{ role_str }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>


        <div class="form-group row">
            <label for="id_balance" class="col-5 col-form-label">Текущий баланс</label>
            <div class="col-7">
                {{ object.balance|stringformat:'s' }}
            </div>
        </div>

        {% if balance_update_allowed %}
        <div class="form-group row">
            <label for="id_balance_delta" class="col-5 col-form-label">Пополнить баланс</label>
            <div class="col-7">
                <input class="form-control" id="id_balance_delta" type="number" step="0.01"
                       name="{{ form.balance_delta.name }}"
                       value="{{ 0.00|stringformat:'s' }}"
                        {% if form.balance_delta.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
        </div>
        {% endif %}

        <div class="form-group row">
            <label for="id_phone" class="col-5 col-form-label">Телефон</label>
            <div class="col-7">
                <input class="form-control" id="id_phone" type="text" name="{{ form.phone.name }}"
                       required="" value="{{ form.phone.initial|default_if_none:'' }}"
                        {% if form.phone.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.phone.errors %}
                <div class="alert alert-danger">
                    {{ form.phone.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label for="id_birth_date" class="col-5 col-form-label">Дата рождения</label>
            <div class="col-7">
                <input class="form-control" id="id_birth_date" type="date" name="{{ form.birth_date.name }}"
                       required="" value="{{ object.birth_date|date:'Y-m-d' }}"
                        {% if form.birth_date.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.birth_date.errors %}
                <div class="alert alert-danger">
                    {{ form.birth_date.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label for="id_delivery_address" class="col-5 col-form-label">Адрес доставки</label>
            <div class="col-7">
                <input class="form-control" id="id_delivery_address" type="text"
                       name="{{ form.delivery_address.name }}"
                       required="" value="{{ form.delivery_address.initial|default_if_none:'' }}"
                        {% if form.delivery_address.field.disabled %}
                       disabled=""
                        {% endif %}
                >
            </div>
            {% if form.delivery_address.errors %}
                <div class="alert alert-danger">
                    {{ form.delivery_address.errors }}
                </div>
            {% endif %}
        </div>

    </form>
    <div class="form-actions text-center">
        <button form="setting" type="submit" class="btn btn-secondary">Сохранить</button>
        <a class="btn btn-secondary" href="{% url 'main:password_change' %}">Сменить пароль</a>
        <a class="btn btn-secondary" href="{% url 'main:delete_user' pk=object.pk %}">Удалить пользователя</a>
    </div>
    </div>

    <script src="{% static '/js/toasts_notifications.js' %}"></script>
    <script src="{% static '/js/name_to_photo.js' %}"></script>
{% endblock content %}

main/templates/main/zakazschik.html
{% extends 'base.html' %}

{% block title %}Опты{% endblock title %}

{% block content %}

    <h3 class="font-weight-normal text-center py-3 mb-3 border-bottom box-shadow">Личный кабинет</h3>
    <div class="container">
    <nav class="nav flex-column">
        <a class="nav-link active" href="{% url 'main:new_order' %}">Новый заказ</a>
        <a class="nav-link active" href="{% url 'main:orders' %}">Мои заказы</a>
        <a class="nav-link" href="{% url 'main:catalog' %}">Выкупы</a>
{#        <a class="nav-link" href="{% url 'main:providers' %}">Поставщики</a>#}
{#        <a class="nav-link" href="{% url 'main:help' %}">Помощь</a>#}
    </nav>
</div>
{% endblock content %}

main/templates/main/zakupschik.html
{% extends 'base.html' %}

{% block title %}Закупщик{% endblock title %}


{% block content %}
    <div class="container">
        <div class="h3 mb-3 font-weight-normal">
            <a href="{% url 'main:zakupschik_places' %}">Места с новыми заказами</a>
        </div>
        <div class="h3 mb-3 font-weight-normal">
            <a href="{% url 'main:zakupschik_products_ready_to_delivery' %}">Товары, готовые к выдаче</a>
        </div>
    </div>
{% endblock content %}

main/templates/main/zakupschik_locations_lines.html
{% extends 'base.html' %}

{% block title %}Заказы{% endblock title %}


{% block content %}
    {% include 'main/include/main_title_template.html' with title='Линии' %}

    <div class="container my-3 p-3 bg-white rounded shadow-sm">
        <div class="list-group">
        {% for line in lines %}
            <a class="list-group-item list-group-item-action"  href="{% url 'main:zakupschik_places' location=location floor=floor line=line %}">Линия: {{ line }} </a>
        {% endfor %}
        </div>
    </div>
{% endblock content %}